"go configuration
"filetype off
"filetype plugin indent off
"set runtimepath+=$GOROOT/misc/vim
"filetype plugin indent on
"syntax on

"Improve autocompletion
"set completeopt=longest,menuone
"inoremap <expr> <CR> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"
"inoremap <expr> <C-n> pumvisible() ? '<C-n>' : '<C-n><C-r>=pumvisible() ? "\<lt>Down>" : ""<CR>'
"inoremap <expr> <M-,> pumvisible() ? '<C-n>' : '<C-x><C-o><C-n><C-p><C-r>=pumvisible() ? "\<lt>Down>" : ""<CR>'
"let g:SuperTabDefaultCompletionType = "<C-x><C-o>"

"indenting
set tabstop=4
set shiftwidth=4
set expandtab
set autoindent

"remap 'q' to quit.
nmap q :q<CR>

"Emulate windows ctrl-c in visual mode using xclip
vmap <C-c> !xclip -selection clipboard -f<CR>
